<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>autolabor_bringup</name>
  <version>0.0.0</version>
  <description>System bringup package for launching the Autolabor Pro1 ROS 2 stack.</description>
  <maintainer email="zhangfei98776@gmail.com">zyj</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>autolabor_navigation</exec_depend>
  <exec_depend>autolabor_driver</exec_depend>
  <exec_depend>autolabor_mapping</exec_depend>
  <exec_depend>autolabor_description</exec_depend>
  <exec_depend>nav2_bringup</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
